// Code generated by qtc from "baseof.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line web/template/baseof.qtpl:1
package template

//line web/template/baseof.qtpl:1
import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
)

//line web/template/baseof.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line web/template/baseof.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line web/template/baseof.qtpl:6
type Page interface {
//line web/template/baseof.qtpl:6
	body() string
//line web/template/baseof.qtpl:6
	streambody(qw422016 *qt422016.Writer)
//line web/template/baseof.qtpl:6
	writebody(qq422016 qtio422016.Writer)
//line web/template/baseof.qtpl:6
	head() string
//line web/template/baseof.qtpl:6
	streamhead(qw422016 *qt422016.Writer)
//line web/template/baseof.qtpl:6
	writehead(qq422016 qtio422016.Writer)
//line web/template/baseof.qtpl:6
	lang() string
//line web/template/baseof.qtpl:6
	streamlang(qw422016 *qt422016.Writer)
//line web/template/baseof.qtpl:6
	writelang(qq422016 qtio422016.Writer)
//line web/template/baseof.qtpl:6
	t(format message.Reference, args ...any) string
//line web/template/baseof.qtpl:6
	streamt(qw422016 *qt422016.Writer, format message.Reference, args ...any)
//line web/template/baseof.qtpl:6
	writet(qq422016 qtio422016.Writer, format message.Reference, args ...any)
//line web/template/baseof.qtpl:6
	title() string
//line web/template/baseof.qtpl:6
	streamtitle(qw422016 *qt422016.Writer)
//line web/template/baseof.qtpl:6
	writetitle(qq422016 qtio422016.Writer)
//line web/template/baseof.qtpl:6
}

//line web/template/baseof.qtpl:15
type BaseOf struct {
	language language.Tag
	printer  *message.Printer
	name     string
}

func NewBaseOf(lang language.Tag, name string) *BaseOf {
	return &BaseOf{
		language: lang,
		printer:  message.NewPrinter(lang),
		name:     name,
	}
}

//line web/template/baseof.qtpl:31
func (p *BaseOf) streamlang(qw422016 *qt422016.Writer) {
//line web/template/baseof.qtpl:31
	qw422016.N().S(` `)
//line web/template/baseof.qtpl:32
	qw422016.E().S(p.language.String())
//line web/template/baseof.qtpl:32
	qw422016.N().S(` `)
//line web/template/baseof.qtpl:33
}

//line web/template/baseof.qtpl:33
func (p *BaseOf) writelang(qq422016 qtio422016.Writer) {
//line web/template/baseof.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/baseof.qtpl:33
	p.streamlang(qw422016)
//line web/template/baseof.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line web/template/baseof.qtpl:33
}

//line web/template/baseof.qtpl:33
func (p *BaseOf) lang() string {
//line web/template/baseof.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/baseof.qtpl:33
	p.writelang(qb422016)
//line web/template/baseof.qtpl:33
	qs422016 := string(qb422016.B)
//line web/template/baseof.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/baseof.qtpl:33
	return qs422016
//line web/template/baseof.qtpl:33
}

//line web/template/baseof.qtpl:35
func (p *BaseOf) streamtitle(qw422016 *qt422016.Writer) {
//line web/template/baseof.qtpl:35
	qw422016.N().S(` `)
//line web/template/baseof.qtpl:36
	qw422016.E().S(p.name)
//line web/template/baseof.qtpl:36
	qw422016.N().S(` `)
//line web/template/baseof.qtpl:37
}

//line web/template/baseof.qtpl:37
func (p *BaseOf) writetitle(qq422016 qtio422016.Writer) {
//line web/template/baseof.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/baseof.qtpl:37
	p.streamtitle(qw422016)
//line web/template/baseof.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line web/template/baseof.qtpl:37
}

//line web/template/baseof.qtpl:37
func (p *BaseOf) title() string {
//line web/template/baseof.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/baseof.qtpl:37
	p.writetitle(qb422016)
//line web/template/baseof.qtpl:37
	qs422016 := string(qb422016.B)
//line web/template/baseof.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/baseof.qtpl:37
	return qs422016
//line web/template/baseof.qtpl:37
}

//line web/template/baseof.qtpl:39
func (p *BaseOf) streamhead(qw422016 *qt422016.Writer) {
//line web/template/baseof.qtpl:39
	qw422016.N().S(` `)
//line web/template/baseof.qtpl:40
	qw422016.N().S(` <link rel="icon" href="/static/favicon.ico" sizes="any"> <link rel="icon" href="/static/icon.svg" type="image/svg+xml"> <link rel="apple-touch-icon" href="/static/apple-touch-icon.png"> <link rel="manifest" href="/static/manifest.webmanifest"> `)
//line web/template/baseof.qtpl:54
}

//line web/template/baseof.qtpl:54
func (p *BaseOf) writehead(qq422016 qtio422016.Writer) {
//line web/template/baseof.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/baseof.qtpl:54
	p.streamhead(qw422016)
//line web/template/baseof.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line web/template/baseof.qtpl:54
}

//line web/template/baseof.qtpl:54
func (p *BaseOf) head() string {
//line web/template/baseof.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/baseof.qtpl:54
	p.writehead(qb422016)
//line web/template/baseof.qtpl:54
	qs422016 := string(qb422016.B)
//line web/template/baseof.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/baseof.qtpl:54
	return qs422016
//line web/template/baseof.qtpl:54
}

//line web/template/baseof.qtpl:56
func (p *BaseOf) streambody(qw422016 *qt422016.Writer) {
//line web/template/baseof.qtpl:56
}

//line web/template/baseof.qtpl:56
func (p *BaseOf) writebody(qq422016 qtio422016.Writer) {
//line web/template/baseof.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/baseof.qtpl:56
	p.streambody(qw422016)
//line web/template/baseof.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line web/template/baseof.qtpl:56
}

//line web/template/baseof.qtpl:56
func (p *BaseOf) body() string {
//line web/template/baseof.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/baseof.qtpl:56
	p.writebody(qb422016)
//line web/template/baseof.qtpl:56
	qs422016 := string(qb422016.B)
//line web/template/baseof.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/baseof.qtpl:56
	return qs422016
//line web/template/baseof.qtpl:56
}

//line web/template/baseof.qtpl:58
func (p *BaseOf) streamt(qw422016 *qt422016.Writer, format message.Reference, args ...any) {
//line web/template/baseof.qtpl:58
	qw422016.N().S(` `)
//line web/template/baseof.qtpl:59
	qw422016.E().S(p.printer.Sprintf(format, args...))
//line web/template/baseof.qtpl:59
	qw422016.N().S(` `)
//line web/template/baseof.qtpl:60
}

//line web/template/baseof.qtpl:60
func (p *BaseOf) writet(qq422016 qtio422016.Writer, format message.Reference, args ...any) {
//line web/template/baseof.qtpl:60
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/baseof.qtpl:60
	p.streamt(qw422016, format, args...)
//line web/template/baseof.qtpl:60
	qt422016.ReleaseWriter(qw422016)
//line web/template/baseof.qtpl:60
}

//line web/template/baseof.qtpl:60
func (p *BaseOf) t(format message.Reference, args ...any) string {
//line web/template/baseof.qtpl:60
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/baseof.qtpl:60
	p.writet(qb422016, format, args...)
//line web/template/baseof.qtpl:60
	qs422016 := string(qb422016.B)
//line web/template/baseof.qtpl:60
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/baseof.qtpl:60
	return qs422016
//line web/template/baseof.qtpl:60
}

//line web/template/baseof.qtpl:62
func StreamTemplate(qw422016 *qt422016.Writer, p Page) {
//line web/template/baseof.qtpl:62
	qw422016.N().S(` <!DOCTYPE html> <html class="page" lang="`)
//line web/template/baseof.qtpl:65
	p.streamlang(qw422016)
//line web/template/baseof.qtpl:65
	qw422016.N().S(`" dir="ltr"> <head> <meta name="viewport" content="width=device-width, initial-scale=1"> <title>`)
//line web/template/baseof.qtpl:72
	p.streamtitle(qw422016)
//line web/template/baseof.qtpl:72
	qw422016.N().S(`</title> <link rel="preload stylesheet" as="style" href="/static/style.css" type="text/css"> `)
//line web/template/baseof.qtpl:79
	p.streamhead(qw422016)
//line web/template/baseof.qtpl:79
	qw422016.N().S(` </head> <body class="page__body cover"> `)
//line web/template/baseof.qtpl:83
	p.streambody(qw422016)
//line web/template/baseof.qtpl:83
	qw422016.N().S(` </body> </html> `)
//line web/template/baseof.qtpl:86
}

//line web/template/baseof.qtpl:86
func WriteTemplate(qq422016 qtio422016.Writer, p Page) {
//line web/template/baseof.qtpl:86
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/baseof.qtpl:86
	StreamTemplate(qw422016, p)
//line web/template/baseof.qtpl:86
	qt422016.ReleaseWriter(qw422016)
//line web/template/baseof.qtpl:86
}

//line web/template/baseof.qtpl:86
func Template(p Page) string {
//line web/template/baseof.qtpl:86
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/baseof.qtpl:86
	WriteTemplate(qb422016, p)
//line web/template/baseof.qtpl:86
	qs422016 := string(qb422016.B)
//line web/template/baseof.qtpl:86
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/baseof.qtpl:86
	return qs422016
//line web/template/baseof.qtpl:86
}
