// Code generated by qtc from "home.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line web/template/home.qtpl:1
package template

//line web/template/home.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line web/template/home.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line web/template/home.qtpl:1
type Home struct {
	*BaseOf
}

//line web/template/home.qtpl:6
func (p *Home) streambody(qw422016 *qt422016.Writer) {
//line web/template/home.qtpl:6
	qw422016.N().S(` <main class="[ body__main ][ stack center ]"> <div class="[ h-app h-x-app ][ text-align_center ]"> <picture> <source srcset="/static/icon.svg" type="image/svg+xml"> <img class="u-icon u-logo u-photo" src="/static/apple-touch-icon.png" loading="lazy" alt="`)
//line web/template/home.qtpl:15
	p.streamt(qw422016, "%s logo", p.name)
//line web/template/home.qtpl:15
	qw422016.N().S(`"> </picture> <h1> <a class="[ u-url ][ p-name ]" href="/">`)
//line web/template/home.qtpl:20
	qw422016.E().S(p.name)
//line web/template/home.qtpl:20
	qw422016.N().S(`</a> </h1> <p class="p-summary">`)
//line web/template/home.qtpl:22
	p.streamt(qw422016, "Dead simple WebSub hub")
//line web/template/home.qtpl:22
	qw422016.N().S(`</p> </div> <hr> <ul class="stack"> <li> <span role="img" aria-label="ping pong"> 🏓 </span> <a rel="external help" hreflang="en" href="https://indieweb.org/how-to-push"> `)
//line web/template/home.qtpl:37
	p.streamt(qw422016, "How to publish and consume?")
//line web/template/home.qtpl:37
	qw422016.N().S(` </a> </li> <li> <span role="img" aria-label="pages"> 📑 </span> <a rel="external help" hreflang="en" href="https://www.w3.org/TR/websub/"> `)
//line web/template/home.qtpl:49
	p.streamt(qw422016, "What the spec?")
//line web/template/home.qtpl:49
	qw422016.N().S(` </a> </li> </ul> </main> `)
//line web/template/home.qtpl:54
}

//line web/template/home.qtpl:54
func (p *Home) writebody(qq422016 qtio422016.Writer) {
//line web/template/home.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/home.qtpl:54
	p.streambody(qw422016)
//line web/template/home.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line web/template/home.qtpl:54
}

//line web/template/home.qtpl:54
func (p *Home) body() string {
//line web/template/home.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/home.qtpl:54
	p.writebody(qb422016)
//line web/template/home.qtpl:54
	qs422016 := string(qb422016.B)
//line web/template/home.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/home.qtpl:54
	return qs422016
//line web/template/home.qtpl:54
}
