// Code generated by qtc from "topic.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line web/template/topic.qtpl:1
package template

//line web/template/topic.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line web/template/topic.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line web/template/topic.qtpl:1
type Topic struct {
	*BaseOf
	Subscribers int
}

//line web/template/topic.qtpl:7
func (p *Topic) streambody(qw422016 *qt422016.Writer) {
//line web/template/topic.qtpl:7
	qw422016.N().S(` <p>`)
//line web/template/topic.qtpl:8
	p.streamt(qw422016, "%d subscribers", p.Subscribers)
//line web/template/topic.qtpl:8
	qw422016.N().S(`</p> `)
//line web/template/topic.qtpl:9
}

//line web/template/topic.qtpl:9
func (p *Topic) writebody(qq422016 qtio422016.Writer) {
//line web/template/topic.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/topic.qtpl:9
	p.streambody(qw422016)
//line web/template/topic.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line web/template/topic.qtpl:9
}

//line web/template/topic.qtpl:9
func (p *Topic) body() string {
//line web/template/topic.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/topic.qtpl:9
	p.writebody(qb422016)
//line web/template/topic.qtpl:9
	qs422016 := string(qb422016.B)
//line web/template/topic.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/topic.qtpl:9
	return qs422016
//line web/template/topic.qtpl:9
}
